# Generated by Django 3.1 on 2020-12-15 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitoparser', '0034_auto_20201215_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoaboutadsavito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 20, 58, 19, 794458), verbose_name='Дата парсинга информации'),
        ),
    ]
