# Generated by Django 3.1 on 2020-10-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerinfo',
            name='accident_rate',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Аварийность'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='address',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='area',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Общая'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='balcony',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Балкон/лоджия'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='bathroom_unit',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Санузел'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='building_type',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Тип дома'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='built_year',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='category_obj',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Категория объекта'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='ceiling_height',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='country',
            field=models.CharField(default='Россия', max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='deadline',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Срок сдачи'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='description',
            field=models.CharField(default='None', max_length=5000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='district',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='district_area',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='finishing',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='flat_plan',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='floor',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='floor_type',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Тип перекрытий'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='gas_supply',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Газоснабжение'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='heating_supply',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Отопление'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='kitchen_space',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='lift',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Лифты'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='living_space',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Жилая'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='parking',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='porch',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Подъезды'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='price',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Информация о стоимомти'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='property_type',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='region',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='renovation',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='room',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='room_space',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Площадь комнаты'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='rooms',
            field=models.CharField(default='None, null=True', max_length=255, verbose_name='Всего комнат в квартире'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='rooms_offered',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Комнат в продажу'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='rooms_space',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Площадь комнат'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='rubbish_chute',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Мусоропровод'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='sales_agent',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Информация об агенте'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='series_construct',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Строительная серия'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='type_of_housing',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Вторичка/новостройка'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='url',
            field=models.OneToOneField(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='cian_parser.urlsads', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='window_view',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Вид из окон'),
        ),
    ]
