# Generated by Django 3.1 on 2020-08-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='date',
        ),
        migrations.AddField(
            model_name='regions',
            name='transcription',
            field=models.CharField(default='Null', max_length=255, verbose_name='Транскрипция'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
    ]
