# Generated by Django 3.1 on 2020-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0002_auto_20201029_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerinfo',
            name='rooms',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Всего комнат в квартире'),
        ),
    ]
