# Generated by Django 3.1 on 2020-10-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0003_auto_20201029_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerinfo',
            name='floors_total',
            field=models.IntegerField(null=True, verbose_name='Этажей в доме'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='address',
            field=models.IntegerField(null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='ceiling_height',
            field=models.FloatField(null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='floor',
            field=models.IntegerField(null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='price',
            field=models.FloatField(null=True, verbose_name='Информация о стоимомти'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='room_space',
            field=models.FloatField(null=True, verbose_name='Площадь комнаты'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='rooms_offered',
            field=models.IntegerField(null=True, verbose_name='Комнат в продажу'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='rooms_space',
            field=models.FloatField(null=True, verbose_name='Площадь комнат'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cian_parser.urlsads', verbose_name='Ссылка'),
        ),
    ]
