# Generated by Django 3.1 on 2020-08-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0004_auto_20200826_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='city',
            field=models.CharField(db_column='Запрос', default='Null', max_length=255),
        ),
    ]
