# Generated by Django 3.1 on 2020-10-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0004_auto_20201029_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serializerinfo',
            name='room',
        ),
    ]
