# Generated by Django 3.1 on 2020-08-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0005_regions_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='city',
            field=models.CharField(default='Null', max_length=255, verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
