# Generated by Django 3.1 on 2020-08-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0006_auto_20200826_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsads',
            name='request',
            field=models.CharField(default='Null', max_length=255, verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='urlsads',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
