# Generated by Django 3.1 on 2020-10-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0006_auto_20201029_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerinfo',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер дома'),
        ),
    ]
