# Generated by Django 3.1 on 2020-10-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0008_remove_serializerinfo_rooms_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serializerinfo',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='area',
            field=models.FloatField(default='None', null=True, verbose_name='Общая'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='built_year',
            field=models.IntegerField(default='None', null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='kitchen_space',
            field=models.FloatField(default='None', null=True, verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='living_space',
            field=models.FloatField(default='None', null=True, verbose_name='Жилая'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='porch',
            field=models.IntegerField(default='None', null=True, verbose_name='Подъезды'),
        ),
    ]
