# Generated by Django 3.1 on 2020-08-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0009_auto_20200828_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationfromads',
            name='price',
            field=models.CharField(default='None', max_length=255, verbose_name='Цена'),
        ),
    ]
