# Generated by Django 3.1 on 2020-10-31 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0009_auto_20201029_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serializerinfo',
            old_name='url',
            new_name='url_ads',
        ),
        migrations.AddField(
            model_name='serializerinfo',
            name='photo_parse_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CianPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('url_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cian_parser.urlsads', verbose_name='Ссылка на объявление')),
            ],
        ),
    ]
