# Generated by Django 3.1 on 2020-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0010_auto_20201031_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serializerinfo',
            name='photo_parse_status',
        ),
        migrations.AddField(
            model_name='informationfromads',
            name='photo_parse_status',
            field=models.BooleanField(default=False),
        ),
    ]
