# Generated by Django 3.1 on 2020-10-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0011_auto_20201031_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationfromads',
            old_name='url',
            new_name='url_ads',
        ),
    ]
