# Generated by Django 3.1 on 2020-10-31 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0012_auto_20201031_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cianphoto',
            name='url_ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cian_parser.informationfromads', verbose_name='Ссылка на объявление'),
        ),
    ]
