# Generated by Django 3.1 on 2020-10-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0013_auto_20201031_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cianphoto',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
