# Generated by Django 3.1 on 2020-10-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0014_auto_20201031_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationfromads',
            old_name='url_ads',
            new_name='inf_url_ads',
        ),
        migrations.RenameField(
            model_name='serializerinfo',
            old_name='url_ads',
            new_name='ser_url_ads',
        ),
    ]
