# Generated by Django 3.1 on 2020-11-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0015_auto_20201031_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cianphoto',
            name='image',
            field=models.ImageField(null=True, upload_to='media/uploads'),
        ),
    ]
