# Generated by Django 3.1 on 2020-11-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0017_auto_20201103_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='CianPhotoStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус скачивания фото')),
            ],
        ),
        migrations.CreateModel(
            name='CianSerializeStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус сериализации обхявления')),
            ],
        ),
    ]
