# Generated by Django 3.1 on 2020-11-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0018_cianphotostatuses_cianserializestatuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationfromads',
            name='new_photo_parse_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cian_parser.cianphotostatuses'),
        ),
        migrations.AddField(
            model_name='informationfromads',
            name='new_serialize_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cian_parser.cianserializestatuses'),
        ),
    ]
