# Generated by Django 3.1 on 2020-11-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0020_auto_20201108_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationfromads',
            old_name='new_photo_parse_status',
            new_name='photo_parse_status',
        ),
        migrations.RenameField(
            model_name='informationfromads',
            old_name='new_serialize_status',
            new_name='serialize_status',
        ),
    ]
