# Generated by Django 3.1 on 2020-11-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0021_auto_20201108_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationfromads',
            name='urls_on_photo',
            field=models.CharField(default='None', max_length=5000, verbose_name='Ссылки на фотографии'),
        ),
    ]
