# Generated by Django 3.1 on 2020-11-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0022_informationfromads_urls_on_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationfromads',
            name='urls_on_photo',
            field=models.CharField(default=None, max_length=5000, null=True, verbose_name='Ссылки на фотографии'),
        ),
    ]
