# Generated by Django 3.1 on 2020-11-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0023_auto_20201109_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsads',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ссылка'),
        ),
    ]
