# Generated by Django 3.1 on 2020-11-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0024_auto_20201110_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAndOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('status', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
