# Generated by Django 3.1 on 2020-11-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0025_sellerandowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlsads',
            old_name='status',
            new_name='status_info_parse',
        ),
        migrations.AddField(
            model_name='urlsads',
            name='status_seller',
            field=models.SmallIntegerField(default=0),
        ),
    ]
