# Generated by Django 3.1 on 2020-11-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0026_auto_20201121_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlsads',
            name='status_seller',
        ),
    ]
