# Generated by Django 3.1 on 2020-11-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0027_remove_urlsads_status_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regions',
            new_name='Region',
        ),
        migrations.AddField(
            model_name='cianphoto',
            name='ser_url_ads',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ser_photos', to='cian_parser.serializerinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cianphoto',
            name='url_ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cian_parser.informationfromads', verbose_name='Ссылка на объявление'),
        ),
    ]
