# Generated by Django 3.1 on 2020-11-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0028_auto_20201128_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerinfo',
            name='urls',
            field=models.CharField(max_length=1000, null=True, verbose_name='Дубль урлов из InformationFromAds'),
        ),
    ]
