# Generated by Django 3.1 on 2020-12-06 18:04

import cian_parser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0030_auto_20201205_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serializerinfo',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='cianphoto',
            name='image',
            field=models.ImageField(null=True, upload_to=cian_parser.models.rand_file_name_path),
        ),
        migrations.AddIndex(
            model_name='urlsads',
            index=models.Index(fields=['phone', 'date', 'url'], name='cian_parser_phone_34c177_idx'),
        ),
    ]
