# Generated by Django 3.1 on 2020-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0031_auto_20201206_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationfromads',
            name='rooms',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cianserializestatuses',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Статус сериализации объявления'),
        ),
    ]
