# Generated by Django 3.1 on 2020-12-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0032_auto_20201211_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerinfo',
            name='urls',
            field=models.CharField(max_length=5000, null=True, verbose_name='Дубль урлов из InformationFromAds'),
        ),
    ]
