# Generated by Django 3.1 on 2020-12-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0033_auto_20201211_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerinfo',
            name='rooms_test',
            field=models.SmallIntegerField(null=True, verbose_name='Всего комнат в квартире'),
        ),
    ]
