# Generated by Django 3.1 on 2020-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0034_serializerinfo_rooms_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serializerinfo',
            name='rooms_test',
        ),
        migrations.AddField(
            model_name='serializerinfo',
            name='rooms_charfield',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Всего комнат в квартире'),
        ),
        migrations.AlterField(
            model_name='serializerinfo',
            name='rooms',
            field=models.SmallIntegerField(null=True, verbose_name='Всего комнат в квартире'),
        ),
    ]
