# Generated by Django 3.1 on 2020-12-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0036_serializerinfo_images_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerinfo',
            name='images_test',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
