# Generated by Django 3.1 on 2020-12-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0037_auto_20201213_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serializerinfo',
            name='images_test',
        ),
    ]
