# Generated by Django 3.1 on 2020-12-15 17:58

import cian_parser.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cian_parser', '0038_remove_serializerinfo_images_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='CianPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=cian_parser.models.rand_file_name_path)),
                ('ser_url_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cian_parser.serializerinfo')),
                ('url_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cian_parser.informationfromads', verbose_name='Ссылка на объявление')),
            ],
        ),
    ]
